### PR TITLE
Added some watering information & UI action

### PR DESCRIPTION
**Pull request by unbirthdays**
Added a "date last watered" field and a UI action to manually change the date to today. Fixed prior issues with some choices. More UI policies. List layout change.
Expect to script based on calculations of when to next water depending on plant type, location, etc.

### CODE REVIEW

**Comment by unbirthdays** [comment]
@404paige hi, I resolved the merge conflicts in this pull request. Could I get a review and merge to move forward?

**Comment by unbirthdays** [comment]
@Lacah unsure who to mention or if specific mods are assigned to specific projects, but looking for a review soon so I can submit a new PR to add things to the instance based off what needed to be removed to resolve previous conflicts with this PR. :) Or please lmk if it would be ok to submit multiple pending PRs at a time without mentioning a mod to approve a previous one!

**Review by Lacah — APPROVED** [review]

**Comment by Lacah** [comment]
@unbirthdays thanks for your contribution and enthusiasm. Apologies if reviews take a bit longer than ideal, we are all volunteers who try to juggle this with our normail jobs and family lives :)
Generally, you should be fine to submit PRs in parallel, especially if you create a new branch for all of them every time.
Thanks!

**Comment by unbirthdays** [comment]
Thanks!

**Pull request merged**
