### PR TITLE
Flow to check daily rain fall and mark plants as watered.

### PR DESCRIPTION
**Pull request by Ramesh-hub007**
Created a flow that runs daily at 23:00 hrs to check for the rainfall data on the current day using an action and update the fields "date_last_watered", "u_watering_due", "rain_in_last_24_hours" using a script include for all locations with plant placement as outdoor.

### CODE REVIEW

**Review by SapphicFire — CHANGES_REQUESTED** [review]
Thank you for your submission. However, it appears that this pull request is incomplete. It lacks guidance around the system property added for Weather API and how to use it. Please complete your contribution by adding the necessary elements and resubmit or update this pull request for further review. Closing this for now. Once you make additional changes, feel free to re-open this Pull Request or create a new one.

**Comment by Ramesh-hub007** [comment]
The Weather API was already available. I have reused it. And it is an open API without any authentication or system property etc

**Comment by SapphicFire** [comment]
Apologies, I see where I misread

**Review by SapphicFire — APPROVED** [review]
Looks good to me

**Pull request merged**
