### PR TITLE
Enhance Plant Trading Table: Auto-Populate Plant Location Field

### PR DESCRIPTION
**Pull request by Dhruvyadav2000**
This PR implements the auto-population of the plant location field in the Plant Trading table. 
The plant location field has been changed to "translated text" and set to read-only. 
Additionally, a Script Include and client script have been created to automatically populate the field based on the selected plant record, enhancing user experience and ensuring data accuracy.

### CODE REVIEW

**Comment by Dhruvyadav2000** [comment]
Hi @am-shakeel, any update on this?

Regards

**Comment by am-shakeel** [comment]
Hi @Dhruvyadav2000 , is there any reason to use the **translated text** field type?

**Comment by Dhruvyadav2000** [comment]
@am-shakeel Actually I am copying plants location value from plants record selected by user and pasting it inside plant_location field on the Plant_Trading form. So that's why I changed this field's type from Reference(created by me only earlier) to Translated Text. 
And since it is read only field, user will not be allowed to change location from here.

**Comment by am-shakeel** [comment]
Hi @Dhruvyadav2000 ,
We can auto-populate the location name by using a reference field as well.

**In the Plants Table**: the Location field **references the Location Table**.
image

**In the Plant Trading Table**: I can see that the location field **references the Plants Table**.
image

We can achieve the same by changing the **reference table(Location)** in the plant_location field instead of changing the field type.

**Comment by Dhruvyadav2000** [comment]
@am-shakeel, Making it a reference field enables a magnifying glass icon for the user, suggesting that they can select a plant location, which doesn't make sense and should not be allowed. While we could make it read-only, using a text field with copied location details makes more sense.

**Comment by am-shakeel** [comment]
If you go with the reference field and make it read-only, you won't be able to see the magnifying glass icon.

**Comment by Dhruvyadav2000** [comment]
@am-shakeel, This way anyhow it will become same as having a translated text read only field. 
Any advantage of having it as a reference field this way?

**Review by am-shakeel — CHANGES_REQUESTED** [review]
@Dhruvyadav2000 - It’s generally not recommended to change the field. If you can achieve this with the existing field type, please go with that only. Please make the changes accordingly. We encourage contributors to review the project's objectives and guidelines (see the README.md and CONTRIBUTING.md files) before submitting pull requests. Closing this for now. Once you make additional changes, feel free to re-open this Pull Request or create a new one.

**Comment by Dhruvyadav2000** [comment]
Hi @am-shakeel, 
Thank you for the feedback! I understand the importance of maintaining the existing field type. I have reviewed the project’s objectives and guidelines and made the necessary adjustments accordingly. 
I have made the necessary changes(tested thoroughly as well) and created a new pull request (#464).

I appreciate your guidance and look forward to contributing further!

Best regards,
Dhruv Yadav

**Pull request closed without merging**
