### PR TITLE
Added a Plant record and included pottery section and fields

### PR DESCRIPTION
**Pull request by Vishnu-rvk**
Added rose details

### CODE REVIEW

**Comment by Vishnu-rvk** [comment]
Hello @earlduque, Im a newbie to GitHub and Hacktoberfest! Is there anything else I need to do! or just wait for assignees to verify?

**Comment by 404paige** [comment]
@Vishnu-rvk You just wait for one of us to verify it (or provide feedback if something needs to change)

**Comment by 404paige** [comment]
And I've already got feedback :) You may want to separate these changes out into multiple Pull Requests. Right now, if I accept it as it, it only counts as a single PR for Hacktoberfest. If that's ok, I can proceed. If you'd like to count as three PRs (one for each commit) I'd recommend breaking it up!

**Review by 404paige — APPROVED** [review]

**Comment by Lacah** [comment]
Fixed conflicts.

**Pull request merged**
