### PR TITLE
Created Holy Basil Plants

### PR DESCRIPTION
**Pull request by bird-03**
Created Basil Plants to 'x_snc_plants_db_plantipedia' table.

### CODE REVIEW

**Comment by bird-03** [comment]
Hi There

While creating PR I got checksum error for write access to repo. Please see details below and help with merge.

<<<<<<< bird_03plantsoct2023
r1RT5B11uUmfnojURzRo4mNYJu8WztNLlYGifANUQ7Nj27QLAlnt9-E5PhSRLHEfbxUiJi4trR_qQkRbXA5k9p4dFHn_mR8xgnTNI-oP4-sRe_9Otq5Sit8o9in5TEadCj9wnxgAjFimFt8HjRluH_6_ThlFOFQN-A97jZqqK4YzcBOgGUpyLAuWaJsE0wOmZjcxDQiEWiViaIZaUXUDmkgnewKTylSi0R4Ej2HSD6srtA4nJtemBMBKgjmPd9cQhNa_TnmxYkEVJooZjtT3bUy9RMRoehnU76e6ceW7YcBHGawJQvYg-QJ8ZGk_REj6AeLrZje_nhdEA5Ok7OyhDjKEz_VHdh-hIOB9rqiUUDPrrclmi-lo2URltZ4qW7KGftmtC-WW6zXtYlip1722aZE03U1-fDx5oRjvhEPn63l661MORDLPnnc-9nBvAzpRbi1KJnZc1oLyP5uMylzn5nQoKfecNo12T6PsyuCUqf2-nXy7h6R9eCw0EgcGEsR4rJ7ciTsmiGgG50hJNrOIQaY1-tPfOnTavxBw3hAgwWjGei3JJXBx1n47HFcIDCvVhPAvXMIeAwwmeAOhrUK0u2IBbQA-xnQago0v8goMIFIVIUgvkRM82-cPdEi5ROWYl9yL31AZRwA5-lHEIhj01Bue9gHWc4c6Vt423HYdgag
=======
UMnLF4uUIJOS8VRBsw6BLUBXat1SfFicG_PG0pxrm3HJFZmLX8Kict-3BiiGVP0XWgtuZQVx1XQfTgqNq4SzSYQ8E5NJVt2ftBhYIo0tqgndCl9ZH2oTdup_SOTfRBUruIg6QPgNEgdu32uht5gOXFVudz1vcd5M3Z466ZAECSvzt1OF4MJLzMaLygUxDTWGUj4UWcEWYr1UNv6MCDEMLCycRLxRhlfK425K-LumGeaWj1Q-d3wlvO5E_kNPZz2iIq4rQMHEjv9DEz2iE52hr1kQSZEfS8JaYqeFqtt_Wda483K28S2HkV6lWNTe1hK0ASgrQuf6aqhbqV8ydmwFc9uvQrAx40bbchEOu35siqQbi16DSZMpF7KnKD-M58n91jxbIM6pIsX6ofZAZD5VAeHPSensifHXv0L3LCCnytvx3nsHZIQTrkL1ntK6V676c4onllpGGOV4Yor6auldh9gdtRxjCY_uTi1VpRhofwzwYts72AT0EnmhPIoH_Z6ruTSrQDeF3oLKWV6uWkg5RkEI4i1ff_aH5oEcTFECSX1Zrsa-Ao4P5VKuBgZiV3FqFKYqZ1ZTeU0cxsYS4ZIsWy1J4wobVF8Q7YOAHa8ZjTldBWdp2DxqjnhQ1RtyH8fsdNJwSY-gf9gDe4bf3VST9hqRURihSL9pwFPe3Jflv9I
>>>>>>> main


Thanks
Abhishek Pandey

**Comment by paigesndev** [comment]
Hello! The description of your submission (Adding Holy Basil Plant) does not appear to match the files that were changed. I see what appears to be a new table with ACLs instead of an entry on the existing table. Can you please either clarify what's in this submission, or we can close this submission and a new one can be submitted that only contains the addition of a plant on the existing tables.

Thank you.

**Comment by bird-03** [comment]
Hi Paige

Thanks for response

I was trying to submit new plant and submit PR. Not sure how ACL changes
include,ight bebi was doing some testing.

If PR can be include by ignoring the ACL changes then it will be helpful.
In other case I will create new branch and merge as only option.

Thanks

**Comment by Lacah** [comment]
@bird-03 I recommend creating a new branch and committing only relevant files to it, then submitting that as a new PR. I will close this one now.

P.s.: no need to worry about checksum error. We will handle that manually for your PR during review.

**Pull request closed without merging**
