### PR TITLE
Rose lilly plant

### PR DESCRIPTION
**Pull request by ravichandra1998g**
added Rose lilly plant in my plants table along with picture, status and maintenance details.

### CODE REVIEW

**Comment by ravichandra1998g** [comment]
removed an extra file that got captured.

**Comment by sandeepd26** [comment]
Thanks for your submission. It appears that this pull request contains more files than described in the title. Please review and update the pull request to either remove the extra/unintended files or to update the description to be more comprehensive. Ensure your contributions are meaningful and adhere to the project’s standards. [If applicable: You can create a new branch on your forked repository to avoid accidental inclusions of new commits in the future.]. Closing this for now. Once you make additional changes, feel free to re-open this Pull Request or create a new one.

You can also provide correct Description , as per the current description : 
"added Rose lilly plants in my plants table along with status and main…
added Rose lily plant along with status and maintenance "

This means you have done the same configuration twice and commited.

**Comment by sandeepd26** [comment]
Kindly work on the Review comments provided.

**Comment by ravichandra1998g** [comment]
I have already removed those extra files Sandeep. You can check in the comments.

**Pull request closed without merging**
