### PR TITLE
New plant record added

### PR DESCRIPTION
**Pull request by Saileshlanka**
Created a new plant record [Coral Berry] in the plantopedia table as an initial exercise.

### CODE REVIEW

**Comment by SapphicFire** [comment]
Hi @Saileshlanka - good contribution. May I ask why you closed your PR, are you planning on making additional changes, no longer wish to contribute, or otherwise don't want this PR addressed?

**Comment by Saileshlanka** [comment]
Hi
Thank you for your reply.
It was a valid submission, as I've tried to rehearse my first PR.
Apparently I thought I should submit everything at a later date in one go
which is why I closed off the PR.
I'm happy if that can be considered now.
Apologies.

**Comment by SapphicFire** [comment]
Happy for you to re-open this if you'd like, for us to then review

**Comment by Saileshlanka** [comment]
Thank you @SapphicFire , I reopened my pull request :)

**Pull request merged**
