### PR TITLE
A pplats03 hack2023

### PR DESCRIPTION
**Pull request by bird-03**
Azadirachta Indica [Neem] new plant added.

### CODE REVIEW

**Comment by earlduque** [comment]
Thanks for your submission. It appears that this pull request contains more files than described in the title. Please review and update the pull request to either remove the extra/unintended files or to update the description to be more comprehensive. Ensure your contributions are meaningful and adhere to the project’s standards. 

In particular, several ACL changes were injected into the app via this PR.

**Comment by earlduque** [comment]
We'll keep the PR open for now in case you can make fixes, so that it can potentially still qualify for Hacktoberfest (it just had to be opened during October, it can still be approved after October). We will likely close stale PRs in one week.

**Review by earlduque — CHANGES_REQUESTED** [review]
Unintended inclusion of files

**Comment by bird-03** [comment]
Hi Earl 

Thanks for the 
PLants AP
response though i don't see any option to delete these files. Seems access issue.

Regards
Abhishek Pandey

**Comment by bird-03** [comment]
Hi Earl

Thanks for your response and guidance.

Have created new branch and PR #187. Hope this has right config file for
acceptance.

New Plant Added as Neem #187

Regards


*Abhishek Pandey*
*+91 7869881249 || ***@***.*** ***@***.***>*

**Pull request closed without merging**
