### PR TITLE
Added the potting information to 4 different plants

### PR DESCRIPTION
**Pull request by selvarun-umass**
Added the potting information to 4 different plants:

Porcelain Flower Verticillata
Chinese Money
Dill
Jasmine

### CODE REVIEW

**Comment by selvarun-umass** [comment]
@Lacah Good morning!

I wanted to check if there’s anything I need to do on my end to help resolve the conflicts. Thank you!

Best,
Selva

**Comment by Lacah** [comment]
Hi Selva,

I'm afraid not. I simply labelled it because this PR contains more complex conflicts, that I was not able to resolve on all of my devices. Nothing for you to do for now, appreciate your patience.

Thanks,
Laszlo

**Comment by selvarun-umass** [comment]
> Hi Selva,
> 
> I'm afraid not. I simply labelled it because this PR contains more complex conflicts, that I was not able to resolve on all of my devices. Nothing for you to do for now, appreciate your patience.
> 
> Thanks, Laszlo

Ok, thank you so much!

Take Care.

**Comment by selvarun-umass** [comment]
@Lacah Thank you so much for merging it.

**Pull request merged**
