### PR TITLE
Created a Plant named as Raj-Plant with Location.

### PR DESCRIPTION
**Pull request by valaparlasalmonraj**

### CODE REVIEW

**Comment by Lacah** [comment]
It appears that this contribution resembles spam, potentially aiming to game the Hacktoberfest event. As a reminder, submissions marked as spam may lead to account restrictions or disqualifications. Please ensure to make unique and meaningful contributions, and refrain from spamming or duplicating submissions. Closing this as spam.

**Comment by valaparlasalmonraj** [comment]
May know particular reason, why this is making as "SPAM".

**Review by wiz0floyd — CHANGES_REQUESTED** [review]
Low effort contributions will be treated as spam.

**Comment by wiz0floyd** [comment]
Please submit a real plant.

**Pull request closed without merging**
