### PR TITLE
Button on Plant wiki page

### PR DESCRIPTION
**Pull request by Rampriya-S**
Added button on Wiki page to navigate Plants Trading page.

Updates:
 1 - Button
 1 - Row
 6 - Columns
 1 - Continer

### CODE REVIEW

**Comment by sandeepd26** [comment]
It appears that this contribution is a duplicate or resembles spam, potentially aiming to game the Hacktoberfest event. As a reminder, submissions marked as spam may lead to account restrictions or disqualifications. Please ensure to make unique and meaningful contributions, and refrain from spamming or duplicating submissions. Closing this as spam.

#360 PR from you contains the same commits as this PR.

**Comment by Rampriya-S** [comment]
Hi @sandeepd26 This button is on Plant Wiki page, the previous one is on Plants trading page please read the description.
image

**Comment by sandeepd26** [comment]
image
The above commit is not part of this PR or description provided unfortunately.
Please create a new branch and create PR.

**Comment by Rampriya-S** [comment]
@sandeepd26, yes I have added 'Plant Trading' button in Plant wiki page.

**Review by SapphicFire — APPROVED** [review]
Looks good to me, thank you

**Pull request merged**
